{"name": "test_Verify_error_displayed_when_invalid_username_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "f9ff7dcf-694e-457e-9bb1-91aeadafe809-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "a2074f8e-38b0-4157-9163-58be66a64902-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['notexist@mail.com']"}], "start": 1623557156080, "stop": 1623557168280, "uuid": "5db13563-c109-4a44-8272-bfaac8707075", "historyId": "a79a86d16a4d43e77cc7c62e2e1d8c05", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "25292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}