{"name": "test_Verify_error_displayed_when_invalid_password_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "105d6f3c-e4f6-4e5a-8e9c-1f7b020800fd-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "588cb7b0-d266-484d-b971-065470357450-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "75aa9853-bf67-46b3-b9ab-2ee820974e62-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['mmhazel.yu@gmail.com', 'isinvalid']"}], "start": 1623560859928, "stop": 1623560868695, "uuid": "1ba080a3-4179-487e-87db-74f2bbad3f79", "historyId": "ccadd074f89991cdfb7fb393a4ae1469", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}